### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by crnkjck** [mcifra/prieskumnik-struktur#1]
Zdá sa, že parser je už viac-menej hotový. Dúfam, že `error()` funguje tak, ako treba, ale teraz. Ostáva dokončiť atomické formuly s rovnosťou a nejaké detaily.

* [x] Super, že si spravil parsovanie termov. Nie je ale dobré, že sa `term` používa ako atomická formula, pretože atomická formula musí začínať predikátovým symbolom, kým term začína funkčným symbolom. Tieto dva prípady treba oddeliť.
* [x] Testovanie **druhov symbolov** je asi lepšie zapísať ako samostatné pravidlá `constant_symbol`, `function_symbol`, `predicate_symbol` a `variable_symbol` pomocou operátora <code>& { <var>predicate</var> }</code>. Pozri [definíciu](https://github.com/pegjs/pegjs#--predicate-). Napr. `ident1:identifier & { ident1 == "x" } "+" ident2:identifier & { ident1 == ident2  }` by malo sparsovať iba string "x+x".
  Oproti `error()` to má výhodu, že parser bude skúšať iné možnosti, kým `error()` vyhodí výnimku a hneď skončí. Dôležité je to pri odlišovaní predikátových a rovnostných atómov.
* [x] **Premenná** je každý identifikátor, ktorý nie je symbolom konštanty, ale ani funkčným ani predikátovým symbolom. Syntax pre kvantifikovanú premennú nie je konzistentná medzi kvantifikátormi navzájom ani so syntaxou identifikátora.
* [x] Pravidlo pre **identifikátor**. Chceme unikódové znaky v identifikátoroch (prinajmenšom slovenskú diakritiku). Keďže pegjs (zatiaľ) nemá knižnicu štandardných pravidiel na triedy unikódových znakov, bude najlepšie využiť pravidlá pre tieto triedy, ktoré sú definované [v príkladoch k pegjs](/pegjs/pegjs/blob/master/examples/javascript.pegjs#L148). Do kódu treba napísať, odkiaľ pochádzajú. Ak sa dajú do gramatiky includovať iné gramatiky, bude najlepšie dať definície unikódových tried do samostatného súboru a includovať ich. Ak nie, mám iné riešenie (osobne).
* [x] **`terms`** je výhodnešie zapísať pomocou opakovacieho operátora `*`. Pozri [definíciu](https://github.com/pegjs/pegjs#expression-) a [príklad](https://pegjs.org/online) – výsledkom tohto operátora je rovno pole. 
* [x] Doplň **test** parsera. Napríklad sa dajú skombinovať testy `toString` z [formula.test.js](/mcifra/prieskumnik-struktur/blob/master/src/tests/formula.test.js) a [tablovača](/FMFI-UK-1-AIN-412/tableauEditor/blob/tests/tests/FormulaTest.elm#L47).
* [x] **Rovnostné atómy** majú tvar <code><var>term</var> = <var>term</var></code>, zátvorky podľa našej syntaxe okolo rovnosti nie sú. Komplikovanejší test na parsovanie formúl s rovnosťou by mohol byť `\a y((\e x g(x,y) = f(y) & p(y)) -> (p(f(y)) \/ g(f(y),y) = f(c))` v jazyku s predikátovým symbolom p/1, s funčnými symbolmi f/1 a g/2 a so symbolom konštanty c.
* [x] Bolo by fajn parsovať aj skratku **negácie rovnosti** <code><var>term</var> != <var>term</var></code>, <code><var>term</var> &lt;&gt; <var>term</var></code>, <code><var>term</var> /= <var>term</var></code>, <code><var>term</var> ≠ <var>term</var></code> na príslušnú skrátenú formulu `Negation EqualityAtom(t1, t2)`.
* [x] Prosím doplň **alternatívne syntaxe** symbolov:
    * negácia: `\lnot`,
    * disjunkcia: `\lor`,
    * exist. kvant.: `\e`, `\E`,
    * všeob. kvant.: `\a`, `\A`.
* [x] Za LaTeXovitými zápismi symbolov by mala byť povinne aspoň jedna medzera.

**Comment by mcifra** [comment]
@crnkjck, stále nerozumiem ako funguje operátor `& { predicate }`. vyskúšal som ten príklad a nedokáže ho sparsovať

```
start 
    = plus
    
plus
    = ident1:identifier & { ident1 == "x" } "+" ident2:identifier & { ident1 == ident2 }
    
identifier
    = $ [a-z]+
```
vyhodí chybu pri vstupe `x+x`

> Line 1, column 2: Expected [a-z] but "+" found.

**Comment by crnkjck** [comment]
Aha, mal som si to otestovať pred odoslaním. :blush: Správne to má byť takto:

	plus
		= ident1:identifier & { return ident1 == "x"; } "+" ident2:identifier & { return ident1 == ident2; }

Boolovská hodnota z testu sa musí `return`-ovať.

Operátor `&` má hodnotu `undefined`, takže napr. `$ [a-z]+ & { return true; }` má hodnotu `Array [ "string", undefined ]`. Ak chceš matchnúť identifikátor a potom otestovať, či má nejakú vlastnosť a aj ho vrátiť, celé pravidlo obaliť do zátvoriek a dať pred ne `$`.

Nasledujúci parser akceptuje stringy typov `xnieco+ynieco`, `ynieco+hocico`, `hocico+ynieco`, ale neakceptuje `xnieco+hocico` ani `hocico+volaco`:

    plus
        = ident1:xidentifier "+" ident2:yidentifier
        / ident1:yidentifier "+" ident2:identifier

    xidentifier "x-identifier"
        = $ (ident:identifier & { console.log(ident); return ident.startsWith("x"); })

    yidentifier "y-identifier"
        = $ (ident:identifier & { console.log(ident); return ident.startsWith("y"); })

    identifier "identifier"
        = $ [a-z]+

**Comment by mcifra** [comment]
pri pravidle formula je jedna chyba a to je ze napr pri konjunkcii uz moze byt v left alebo right term alebo formula.
da sa to zapisat takto? 
`"(" left:(formula / term) spaces conjunction_symbol spaces right:(formula / term) ")" {return new Conjunction(left, right)}`

**Comment by mcifra** [comment]
Pravidlo `terms` vracia v prípade počtu termov viac ako 1 pole tvaru 

`[<prvy term>, [ [], ',', [], <druhy term>], [ [], ',', [], <treti term>], ... ]`

Ako by sa dalo prepísať toto pravidlo aby parser vracal pole takéhoto tvaru?

`[<prvy term>, <druhy term>, <treti term>, ...]`

**Comment by crnkjck** [comment]
K tym `formula / term`: Toto nie je správne, binárnymi spojkami sú spojené vždy **iba formuly**. Konjunkcia medzi termami v logike prvého rádu nemá zmysel. Nesedí totiž „typovo“: hodnotou termu nie je pravdivostná hodnota, ale prvok z domény.

**Comment by crnkjck** [comment]
K `terms`: Malo by sa to dať spraviť vložením akcie dovnútra zátvorky:

    … ts:(spaces "," spaces t1:term { return t1; })* …

Viď aj [Action Execution Environment](/pegjs/pegjs#action-execution-environment).

**Comment by mcifra** [comment]
> K tym formula / term: Toto nie je správne, binárnymi spojkami sú spojené vždy iba formuly. Konjunkcia medzi termami v logike prvého rádu nemá zmysel. Nesedí totiž „typovo“: hodnotou termu nie je pravdivostná hodnota, ale prvok z domény.

Ale v existenčnom a všeobecnom kvantifikátore už môžu byť, hej?

**Comment by crnkjck** [comment]
Nie, ani tam. Termy sa dajú použiť iba ako argumenty predikátov, funkcií, v rovnosti a v nerovnosti.

Spojky, negácia aj kvantifikátory priamo obsahujú iba formuly (samozrejme, hneď kvantifikátorom nasleduje viazaná premenná, ale za ňou je formula, nie term; mimochodom, medzi premennou a formulou v kvantifikátore je dovolená medzera).
