### ISSUE TITLE
Zobrazovanie na uzkych displejoch

### ISSUE THREAD

**Issue by crnkjck** [mcifra/prieskumnik-struktur#13]
Na uzkych displejoch su dva problemy so zobrazovanim prieskumnika:

 Problem | Screenshot
---------|-----------
Spravne/Nespravne je blizsie k nasledujucej formule, ako k tej, ktorej sa tyka. Niektorych studentov to na cviceniach plietlo. Prejavi sa to aj pri polovicnej sirke okna na notebooku. Bud by sa mohlo Spravne/Nespravne umiestnit vedla menu (pomer 8:4 by mohol fungovat aj na mensich mobiloch, ale treba otestovat), alebo to chce pridat pod Spravne/Nespravne prazdne miesto ci `hr`, ktore sa bude zobrazovat iba na uzkych displejoch.|![screenshot_20180425-164858](https://user-images.githubusercontent.com/1124733/39253825-120d5f5a-48a9-11e8-9fb3-e39b17ca3ad7.png)
Globalne ovladacie prvky su rozbite. Zrejme ich treba rozlozit do dvoch riadkov. Navyse si myslim, ze prepinac modu by mal byt na sirsich displejoch celkom vpravo.|![screenshot_20180425-164908](https://user-images.githubusercontent.com/1124733/39253836-198ed38a-48a9-11e8-82e4-f51cf5943952.png)

**Comment by mcifra** [comment]
problém vyriešený
